// express-vue/src/views/payment/PaymentSuccess.vue
<template>
  <div class="box_section" style="width: 600px">
    <img
      width="100px"
      src="https://static.toss.im/illusts/check-blue-spot-ending-frame.png"
    />

    <h2>결제를 완료했어요</h2>
    <div class="p-grid typography--p" style="margin-top: 50px">
      <div class="p-grid-col text--left">
        <b>결제금액</b>
      </div>
      <div class="p-grid-col text--right" id="amount">
        {{ Number(route.query.amount).toLocaleString() }}원
      </div>
    </div>

    <div class="p-grid typography--p" style="margin-top: 10px">
      <div class="p-grid-col text--left">
        <b>주문번호</b>
      </div>
      <div class="p-grid-col text--right" id="orderId">
        {{ route.query.orderId }}
      </div>
    </div>

    <div class="p-grid typography--p" style="margin-top: 10px">
      <div class="p-grid-col text--left">
        <b>paymentKey</b>
      </div>
      <div
        class="p-grid-col text--right"
        id="paymentKey"
        style="white-space: initial; width: 250px"
      >
        {{ route.query.paymentKey }}
      </div>
    </div>

    <div class="p-grid-col">
      <a
        href="https://docs.tosspayments.com/guides/v2/payment-window/integration"
        target="_blank"
        rel="noopener noreferrer"
      >
        <button class="button p-grid-col5">연동 문서</button>
      </a>

      <a
        href="https://developers.tosspayments.com/go/techchat"
        target="_blank"
        rel="noopener noreferrer"
      >
        <button
          class="button p-grid-col5"
          style="background-color: #e8f3ff; color: #1b64da"
        >
          실시간 문의
        </button>
      </a>
    </div>
  </div>

  <div
    class="box_section"
    style="width: 600px; text-align: left"
    v-if="responseData"
  >
    <b>Response Data :</b>

    <div id="response" style="white-space: initial">
      <pre>{{ JSON.stringify(responseData, null, 4) }}</pre>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useRoute, useRouter } from "vue-router";

const route = useRoute();
const router = useRouter();

const responseData = ref(null);

async function confirm() {
  const requestData = {
    orderId: route.query.orderId,
    amount: route.query.amount,
    paymentKey: route.query.paymentKey,
  };

  const response = await fetch("/api/confirm/payment", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(requestData),
  });

  const json = await response.json();

  if (!response.ok) {
    throw { message: json.message, code: json.code };
  }

  return json;
}

confirm()
  .then((data) => {
    responseData.value = data;
  })
  .catch((error) => {
    router.replace(`/fail?code=${error.code}&message=${error.message}`);
  });
</script>

// express-react/src/pages/payment/PaymentSuccess.jsx
import { useEffect, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";

export function PaymentSuccessPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [responseData, setResponseData] = useState(null);

  useEffect(() => {
    async function confirm() {
      const requestData = {
        orderId: searchParams.get("orderId"),
        amount: searchParams.get("amount"),
        paymentKey: searchParams.get("paymentKey"),
      };

      const response = await fetch("/api/confirm", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(requestData),
      });

      const json = await response.json();

      if (!response.ok) {
        throw { message: json.message, code: json.code };
      }

      return json;
    }

    confirm()
      .then((data) => {
        setResponseData(data);
      })
      .catch((error) => {
        navigate(`/fail?code=${error.code}&message=${error.message}`);
      });
  }, [searchParams]);

  return (
    <>
      <div className="box_section" style={{ width: "600px" }}>
        <img width="100px" src="https://static.toss.im/illusts/check-blue-spot-ending-frame.png" />
        <h2>결제를 완료했어요</h2>
        <div className="p-grid typography--p" style={{ marginTop: "50px" }}>
          <div className="p-grid-col text--left">
            <b>결제금액</b>
          </div>
          <div className="p-grid-col text--right" id="amount">
            {`${Number(searchParams.get("amount")).toLocaleString()}원`}
          </div>
        </div>
        <div className="p-grid typography--p" style={{ marginTop: "10px" }}>
          <div className="p-grid-col text--left">
            <b>주문번호</b>
          </div>
          <div className="p-grid-col text--right" id="orderId">
            {`${searchParams.get("orderId")}`}
          </div>
        </div>
        <div className="p-grid typography--p" style={{ marginTop: "10px" }}>
          <div className="p-grid-col text--left">
            <b>paymentKey</b>
          </div>
          <div className="p-grid-col text--right" id="paymentKey" style={{ whiteSpace: "initial", width: "250px" }}>
            {`${searchParams.get("paymentKey")}`}
          </div>
        </div>
        <div className="p-grid-col">
          <Link to="https://docs.tosspayments.com/guides/v2/payment-widget/integration">
            <button className="button p-grid-col5">연동 문서</button>
          </Link>
          <Link to="https://discord.gg/A4fRFXQhRu">
            <button className="button p-grid-col5" style={{ backgroundColor: "#e8f3ff", color: "#1b64da" }}>
              실시간 문의
            </button>
          </Link>
        </div>
      </div>
      <div className="box_section" style={{ width: "600px", textAlign: "left" }}>
        <b>Response Data :</b>
        <div id="response" style={{ whiteSpace: "initial" }}>
          {responseData && <pre>{JSON.stringify(responseData, null, 4)}</pre>}
        </div>
      </div>
    </>
  );
}
