// react/src/pages/Checkout.tsx
import { useEffect, useState } from "react";

// TODO: clientKey는 개발자센터의 결제위젯 연동 키 > 클라이언트 키로 바꾸세요.
// TODO: server.js 의 secretKey 또한 결제위젯 연동 키가 아닌 API 개별 연동 키의 시크릿 키로 변경해야 합니다.
// TODO: 구매자의 고유 아이디를 불러와서 customerKey로 설정하세요. 이메일・전화번호와 같이 유추가 가능한 값은 안전하지 않습니다.
// @docs https://docs.tosspayments.com/reference/widget-sdk#sdk-설치-및-초기화
const clientKey = "test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm";
const customerKey = generateRandomString();

const amount = {
  currency: "KRW",
  value: 50_000,
};

export function CheckoutPage() {
  const [ready, setReady] = useState(false);
  // FIXME: 타입 추가
  const [widgets, setWidgets] = useState<any>(null);

  useEffect(() => {
    async function fetchPaymentWidgets() {
      try {
        const tossPayments = TossPayments(clientKey);

        // FIXME: loadPayment 메소드로 변경 필요
        // 회원 결제
        const widgets = tossPayments.widgets({
          customerKey,
        });
        // 비회원 결제
        // const widgets = tossPayments.widgets({customerKey: TossPayments.ANONYMOUS});

        // const loadedWidgets = await loadPaymentWidgets(clientKey, customerKey);
        setWidgets(widgets);
      } catch (error) {
        console.error("Error fetching payment widget:", error);
      }
    }

    fetchPaymentWidgets();
  }, [clientKey, customerKey]);

  useEffect(() => {
    async function renderPaymentWidgets() {
      if (widgets == null) {
        return;
      }

      // ------  주문서의 결제 금액 설정 ------
      // TODO: 위젯의 결제금액을 결제하려는 금액으로 초기화하세요.
      // TODO: renderPaymentMethods, renderAgreement, requestPayment 보다 반드시 선행되어야 합니다.
      await widgets.setAmount(amount);

      // ------  결제 UI 렌더링 ------
      // @docs https://docs.tosspayments.com/reference/widget-sdk#renderpaymentmethods선택자-결제-금액-옵션
      await widgets.renderPaymentMethods({
        selector: "#payment-method",
        // 렌더링하고 싶은 결제 UI의 variantKey
        // 결제 수단 및 스타일이 다른 멀티 UI를 직접 만들고 싶다면 계약이 필요해요.
        // @docs https://docs.tosspayments.com/guides/payment-widget/admin#멀티-결제-ui
        variantKey: "DEFAULT",
      });

      // ------  이용약관 UI 렌더링 ------
      // @docs https://docs.tosspayments.com/reference/widget-sdk#renderagreement선택자-옵션
      await widgets.renderAgreement({
        selector: "#agreement",
        variantKey: "AGREEMENT",
      });

      setReady(true);
    }

    renderPaymentWidgets();
  }, [widgets]);

  return (
    <div className="wrapper">
      <div className="box_section">
        {/* 결제 UI */}
        <div id="payment-method" />
        {/* 이용약관 UI */}
        <div id="agreement" />
        {/* 쿠폰 체크박스 */}
        <div style={{ paddingLeft: "24px" }}>
          <div className="checkable typography--p">
            <label
              htmlFor="coupon-box"
              className="checkable__label typography--regular">
              <input
                id="coupon-box"
                className="checkable__input"
                type="checkbox"
                aria-checked="true"
                disabled={!ready}
                // ------  주문서의 결제 금액이 변경되었을 경우 결제 금액 업데이트 ------
                // @docs https://docs.tosspayments.com/reference/widget-sdk#updateamount결제-금액
                onChange={async (event) => {
                  if (event.target.checked) {
                    await widgets.setAmount({
                      currency: amount.currency,
                      value: amount.value - 5000,
                    });

                    return;
                  }

                  await widgets.setAmount(amount);
                }}
              />
              <span className="checkable__label-text">5,000원 쿠폰 적용</span>
            </label>
          </div>
        </div>

        {/* 결제하기 버튼 */}
        <button
          className="button"
          style={{ marginTop: "30px" }}
          disabled={!ready}
          // ------ '결제하기' 버튼 누르면 결제창 띄우기 ------
          // @docs https://docs.tosspayments.com/reference/widget-sdk#requestpayment결제-정보
          onClick={async () => {
            try {
              // 결제를 요청하기 전에 orderId, amount를 서버에 저장하세요.
              // 결제 과정에서 악의적으로 결제 금액이 바뀌는 것을 확인하는 용도입니다.
              await widgets.requestPayment({
                orderId: generateRandomString(),
                orderName: "토스 티셔츠 외 2건",
                successUrl: window.location.origin + "/success",
                failUrl: window.location.origin + "/fail",
                customerEmail: "customer123@gmail.com",
                customerName: "김토스",
                customerMobilePhone: "01012341234",
              });
            } catch (error) {
              // 에러 처리하기
              console.error(error);
            }
          }}>
          결제하기
        </button>
      </div>
    </div>
  );
}

function generateRandomString() {
  return window.btoa(Math.random().toString()).slice(0, 20);
}

// nuxt4-javascript/app/pages/payment/checkout.vue
<template>
  <div class="wrapper">
    <div class="box_section">
      <h1>일반 결제</h1>

      <div id="payment-method" style="display: flex">
        <button id="CARD" v-bind:class="{ active: selectedPaymentMethod === 'CARD' }" class="button2" @click="selectedPaymentMethod = 'CARD'">카드</button>
        <button id="TRANSFER" v-bind:class="{ active: selectedPaymentMethod === 'TRANSFER' }" class="button2" @click="selectedPaymentMethod = 'TRANSFER'">계좌이체</button>
        <button id="VIRTUAL_ACCOUNT" v-bind:class="{ active: selectedPaymentMethod === 'VIRTUAL_ACCOUNT' }" class="button2" @click="selectedPaymentMethod = 'VIRTUAL_ACCOUNT'">가상계좌</button>
        <button id="MOBILE_PHONE" v-bind:class="{ active: selectedPaymentMethod === 'MOBILE_PHONE' }" class="button2" @click="selectedPaymentMethod = 'MOBILE_PHONE'">휴대폰</button>
        <button
          id="CULTURE_GIFT_CERTIFICATE"
          v-bind:class="{ active: selectedPaymentMethod === 'CULTURE_GIFT_CERTIFICATE' }"
          class="button2"
          @click="selectedPaymentMethod = 'CULTURE_GIFT_CERTIFICATE'"
        >
          문화상품권
        </button>
        <button id="FOREIGN_EASY_PAY" v-bind:class="{ active: selectedPaymentMethod === 'FOREIGN_EASY_PAY' }" class="button2" @click="selectedPaymentMethod = 'FOREIGN_EASY_PAY'">
          해외간편결제
        </button>
      </div>

      <button class="button" @click="requestPayment">결제하기</button>
    </div>

    <div class="box_section">
      <h1>정기 결제</h1>
      <div id="billing-method" style="display: flex">
        <button id="BILLING_CARD" v-bind:class="{ active: selectedBillingMethod === 'CARD' }" class="button2" @click="selectedBillingMethod = 'CARD'">카드 자동결제</button>
        <button id="BILLING_TRANSFER" v-bind:class="{ active: selectedBillingMethod === 'TRANSFER' }" class="button2" @click="selectedBillingMethod = 'TRANSFER'">계좌 자동결제</button>
      </div>
      <button class="button" @click="requestBillingAuth">자동결제 수단 등록하기</button>
    </div>
  </div>
</template>

<script>
import { loadTossPayments } from "@tosspayments/tosspayments-sdk";

function generateRandomString() {
  return window.btoa(Math.random().toString()).slice(0, 20);
}

// TODO: clientKey는 개발자센터의 API 개별 연동 키 > 결제창 연동에 사용하려할 MID > 클라이언트 키로 바꾸세요.
// TODO: server.js 의 secretKey 또한 결제위젯 연동 키가 아닌 API 개별 연동 키의 시크릿 키로 변경해야 합니다.
// TODO: 구매자의 고유 아이디를 불러와서 customerKey로 설정하세요. 이메일・전화번호와 같이 유추가 가능한 값은 안전하지 않습니다.
// @docs https://docs.tosspayments.com/sdk/v2/js#토스페이먼츠-초기화
const clientKey = "test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq";
const amount = {
  currency: "KRW",
  value: 50000,
};

export default {
  data() {
    return {
      payment: null,
      customerKey: "",
      selectedPaymentMethod: "TRANSFER",
      selectedBillingMethod: "CARD",
    };
  },
  methods: {
    async fetchPayment() {
      try {
        this.customerKey = generateRandomString();
        const tossPayments = await loadTossPayments(clientKey);

        // 회원 결제
        // @docs https://docs.tosspayments.com/sdk/v2/js#tosspaymentswidgets
        const payment = tossPayments.payment({ customerKey: this.customerKey });

        this.payment = payment;
      } catch (error) {
        console.error("Error fetching payment:", error);
      }
    },
    async requestPayment() {
      try {
        switch (this.selectedPaymentMethod) {
          case "CARD":
            await this.payment.requestPayment({
              method: "CARD",
              amount,
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
              card: {
                useEscrow: false,
                flowMode: "DEFAULT",
                useCardPoint: false,
                useAppCardOnly: false,
              },
            });
            break;
          case "TRANSFER":
            await this.payment.requestPayment({
              method: "TRANSFER",
              amount,
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
              transfer: {
                cashReceipt: {
                  type: "소득공제",
                },
                useEscrow: false,
              },
            });
            break;
          case "VIRTUAL_ACCOUNT":
            await this.payment.requestPayment({
              method: "VIRTUAL_ACCOUNT",
              amount,
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
              virtualAccount: {
                cashReceipt: {
                  type: "소득공제",
                },
                useEscrow: false,
                validHours: 24,
              },
            });
            break;
          case "MOBILE_PHONE":
            await this.payment.requestPayment({
              method: "MOBILE_PHONE",
              amount,
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
            });
            break;
          case "CULTURE_GIFT_CERTIFICATE":
            await this.payment.requestPayment({
              method: "CULTURE_GIFT_CERTIFICATE",
              amount,
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
            });
            break;
          case "FOREIGN_EASY_PAY":
            await this.payment.requestPayment({
              method: "FOREIGN_EASY_PAY",
              amount: {
                value: 100,
                currency: "USD",
              },
              orderId: generateRandomString(),
              orderName: "토스 티셔츠 외 2건",
              successUrl: window.location.origin + "/payment/success",
              failUrl: window.location.origin + "/fail",
              customerEmail: "customer123@gmail.com",
              customerName: "김토스",
              foreignEasyPay: {
                provider: "PAYPAL",
                country: "KR",
              },
            });
            break;
        }
      } catch (error) {
        console.error(error);
      }
    },
    async requestBillingAuth() {
      await this.payment.requestBillingAuth({
        method: this.selectedBillingMethod,
        successUrl: window.location.origin + `/payment/billing?billingMethod=${this.selectedBillingMethod}`,
        failUrl: window.location.origin + "/fail",
        customerEmail: "customer123@gmail.com",
        customerName: "김토스",
      });
    },
  },
  async mounted() {
    await this.fetchPayment();
  },
};
</script>
